### ISSUE TITLE
languages that aren't linted

### ISSUE THREAD

**Issue by eshellman** [vhf/free-programming-books-lint#14]
Here is the current list of languages covered in the F-P-B repo:

`'ar',
'az',
'bg',
'bl',
'cs',
'de',
'dk',
'en',
'es',
'et',
'fa_IR',
'fi',
'fr',
'gr',
'hi',
'hu',
'id',
'it',
'ja',
'ko',
'kk',
'my',
'nl',
'no',
'pl',
'pt_BR',
'pt_PT',
'ro',
'ru',
'se',
'sk',
'ta',
'th',
'tr',
'ua',
'vi',
'zh',
`

**Comment by eshellman** [comment]
15 of these languages are not considered in the linter.

**Comment by eshellman** [comment]
Is there anything more to do than add these in lint.js?

**Comment by vhf** [comment]
I don't think so, it should just work. There's just one thing to keep in mind: alphabetical ordering isn't something that works with all languages and you'll most probably need advice from native speakers. For instance to my knowledge alphabetically sorting Japanese words is an unsolved problem. The way it will be enforced here is how JavaScript implements it, and the result could very well seem weird/unnatural/unpredictable to Japanese speakers.

**Comment by eshellman** [comment]
I think that's ok

**Comment by eshellman** [comment]
so I tried running this locally (macOS, node 15.6) on the courses list and it reported errors for ko, ru, and vi, which aren't in the list. So I'm confused. (and not much experience with node.)
