### ISSUE TITLE
need more flexible exclude

### ISSUE THREAD

**Issue by eshellman** [vhf/free-programming-books-lint#16]
F-P-B now has translated versions of HOWTO, CONTRIBUTING and CODE_OF_CONDUCT. Translators are surprised that these files are checked for alphabetized lists when the files they are translating aren't checked.

**Comment by vhf** [comment]
Here is the list of excluded files: https://github.com/vhf/free-programming-books-lint/blob/a752787f131b996b031059fa65e456dbb30e87da/lib/lint.js#L6-L11

**Comment by vhf** [comment]
https://github.com/EbookFoundation/free-programming-books/pull/5239
